import { ToolCategory } from './types'

export interface ToolDefinition {
  id: string
  name: string
  description: string
  category: ToolCategory
  keywords: string[]
}

export const toolDefinitions: ToolDefinition[] = [
  // Converters & Formatters
  {
    id: 'json-formatter',
    name: 'JSON Formatter & Validator',
    description: 'Format, validate, and beautify JSON data with syntax highlighting',
    category: 'Converters & Formatters',
    keywords: ['json', 'format', 'validate', 'beautify', 'minify', 'parse'],
  },
  {
    id: 'json-yaml',
    name: 'JSON ↔ YAML Converter',
    description: 'Convert between JSON and YAML formats',
    category: 'Converters & Formatters',
    keywords: ['json', 'yaml', 'convert', 'transform', 'config'],
  },
  {
    id: 'json-csv',
    name: 'JSON ↔ CSV Converter',
    description: 'Convert JSON arrays to CSV and CSV to JSON',
    category: 'Converters & Formatters',
    keywords: ['json', 'csv', 'convert', 'export', 'import', 'spreadsheet'],
  },
  {
    id: 'json-xml', // Converted from xml-json
    name: 'JSON ↔ XML Converter',
    description: 'Convert between JSON and XML formats',
    category: 'Converters & Formatters',
    keywords: ['xml', 'json', 'convert', 'transform'],
  },
  {
    id: 'sql-to-json',
    name: 'SQL to JSON',
    description: 'Convert SQL INSERT statements to JSON data',
    category: 'Converters & Formatters',
    keywords: ['sql', 'json', 'convert', 'insert', 'data', 'database'],
  },
  {
    id: 'json-typescript',
    name: 'JSON to TypeScript',
    description: 'Generate TypeScript interfaces from JSON',
    category: 'Converters & Formatters',
    keywords: ['json', 'typescript', 'interface', 'generate', 'type'],
  },
  {
    id: 'json-go',
    name: 'JSON to Go Struct',
    description: 'Generate Go structs from JSON',
    category: 'Converters & Formatters',
    keywords: ['json', 'go', 'golang', 'struct', 'generate'],
  },
  {
    id: 'json-rust',
    name: 'JSON to Rust Struct',
    description: 'Generate Rust structs from JSON',
    category: 'Converters & Formatters',
    keywords: ['json', 'rust', 'struct', 'generate', 'serde'],
  },
  {
    id: 'base64',
    name: 'Base64 Encode / Decode',
    description: 'Encode text to Base64 or decode Base64 strings',
    category: 'Converters & Formatters',
    keywords: ['base64', 'encode', 'decode', 'convert', 'binary'],
  },
  {
    id: 'url-encode',
    name: 'URL Encode / Decode',
    description: 'Encode or decode URL components and query strings',
    category: 'Converters & Formatters',
    keywords: ['url', 'encode', 'decode', 'uri', 'percent', 'query'],
  },
  {
    id: 'html-entity',
    name: 'HTML Entity Encode/Decode',
    description: 'Convert special characters to HTML entities and vice versa',
    category: 'Converters & Formatters',
    keywords: ['html', 'entity', 'encode', 'decode', 'escape', 'special'],
  },
  {
    id: 'image-base64',
    name: 'Image to Base64',
    description: 'Convert images to Base64 encoded strings and data URLs',
    category: 'Converters & Formatters',
    keywords: ['image', 'base64', 'data url', 'convert', 'encode', 'picture'],
  },
  {
    id: 'image-format',
    name: 'Image Format Converter',
    description: 'Convert between image formats (PNG, JPEG, WebP)',
    category: 'Converters & Formatters',
    keywords: ['image', 'format', 'convert', 'png', 'jpeg', 'webp'],
  },
  {
    id: 'timestamp',
    name: 'Timestamp Converter',
    description: 'Convert between Unix timestamps and human-readable dates',
    category: 'Converters & Formatters',
    keywords: ['timestamp', 'unix', 'date', 'time', 'convert', 'epoch'],
  },
  {
    id: 'color',
    name: 'Color Converter',
    description: 'Convert between HEX, RGB, HSL color formats',
    category: 'Converters & Formatters',
    keywords: ['color', 'hex', 'rgb', 'hsl', 'convert', 'picker'],
  },
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    description: 'Compress PNG, JPEG, and WebP images locally',
    category: 'Converters & Formatters',
    keywords: ['image', 'compress', 'minify', 'reduce', 'size', 'jpeg', 'png', 'webp'],
  },
  {
    id: 'image-cropper',
    name: 'Image Cropper',
    description: 'Crop images with preset ratios or freeform',
    category: 'Converters & Formatters',
    keywords: ['image', 'crop', 'resize', 'cut', 'aspect ratio'],
  },
  {
    id: 'image-filters',
    name: 'Image Filters',
    description: 'Apply CSS-like filters (blur, sepia, grayscale) to images',
    category: 'Converters & Formatters',
    keywords: ['image', 'filter', 'effect', 'edit', 'blur', 'grayscale'],
  },
  {
    id: 'color-extractor',
    name: 'Color Extractor',
    description: 'Extract dominant colors and palettes from images',
    category: 'Converters & Formatters',
    keywords: ['color', 'extract', 'palette', 'image', 'picker', 'dominant'],
  },
  {
    id: 'svg-to-png',
    name: 'SVG to PNG Converter',
    description: 'Convert SVG files or code to high-resolution PNG',
    category: 'Converters & Formatters',
    keywords: ['svg', 'png', 'convert', 'vector', 'raster', 'image'],
  },
  {
    id: 'exif-viewer',
    name: 'EXIF Viewer & Remover',
    description: 'View and strip EXIF metadata from images',
    category: 'Converters & Formatters',
    keywords: ['exif', 'metadata', 'image', 'photo', 'privacy', 'remove'],
  },
  {
    id: 'number-base',
    name: 'Number Base Converter',
    description: 'Convert numbers between binary, octal, decimal, hexadecimal',
    category: 'Converters & Formatters',
    keywords: ['number', 'base', 'binary', 'octal', 'decimal', 'hex', 'convert'],
  },
  {
    id: 'html-formatter',
    name: 'HTML Formatter',
    description: 'Format and beautify HTML with proper indentation',
    category: 'Converters & Formatters',
    keywords: ['html', 'format', 'beautify', 'indent', 'minify'],
  },
  {
    id: 'css-formatter',
    name: 'CSS Formatter',
    description: 'Format and beautify CSS with proper indentation',
    category: 'Converters & Formatters',
    keywords: ['css', 'format', 'beautify', 'indent', 'minify', 'style'],
  },
  {
    id: 'js-formatter',
    name: 'JavaScript Formatter',
    description: 'Format and beautify JavaScript code',
    category: 'Converters & Formatters',
    keywords: ['javascript', 'js', 'format', 'beautify', 'indent', 'minify'],
  },
  {
    id: 'ts-formatter',
    name: 'TypeScript Formatter',
    description: 'Format and beautify TypeScript code',
    category: 'Converters & Formatters',
    keywords: ['typescript', 'ts', 'format', 'beautify', 'indent', 'minify'],
  },
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    description: 'Format and beautify SQL queries',
    category: 'Converters & Formatters',
    keywords: ['sql', 'format', 'beautify', 'query', 'database'],
  },
  {
    id: 'xml-formatter',
    name: 'XML Formatter',
    description: 'Format and beautify XML with proper indentation',
    category: 'Converters & Formatters',
    keywords: ['xml', 'format', 'beautify', 'indent', 'minify'],
  },
  {
    id: 'yaml-formatter',
    name: 'YAML Formatter',
    description: 'Format and beautify YAML with validation',
    category: 'Converters & Formatters',
    keywords: ['yaml', 'yml', 'format', 'beautify', 'indent', 'minify'],
  },
  {
    id: 'python-formatter',
    name: 'Python Formatter',
    description: 'Format Python code',
    category: 'Converters & Formatters',
    keywords: ['python', 'py', 'format', 'beautify'],
  },
  {
    id: 'markdown-html',
    name: 'Markdown → HTML Converter',
    description: 'Convert Markdown to clean HTML',
    category: 'Converters & Formatters',
    keywords: ['markdown', 'html', 'convert', 'md', 'render'],
  },

  // Text & Analysis
  {
    id: 'text-diff',
    name: 'Text Diff/Compare',
    description: 'Compare two text inputs and show differences',
    category: 'Text & Analysis',
    keywords: ['diff', 'compare', 'text', 'difference', 'merge'],
  },
  {
    id: 'regex',
    name: 'Regex Tester',
    description: 'Test regular expressions with live matching and highlighting',
    category: 'Text & Analysis',
    keywords: ['regex', 'regular', 'expression', 'test', 'match', 'pattern'],
  },
  {
    id: 'word-count',
    name: 'Word & Character Counter',
    description: 'Count words, characters, sentences, and paragraphs',
    category: 'Text & Analysis',
    keywords: ['word', 'character', 'count', 'sentence', 'paragraph', 'length'],
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    description: 'Convert text between camelCase, PascalCase, snake_case, and kebab-case',
    category: 'Text & Analysis',
    keywords: ['case', 'camel', 'pascal', 'snake', 'kebab', 'convert', 'text'],
  },
  {
    id: 'cron-explainer',
    name: 'Cron Explainer',
    description: 'Translate cron expressions into human-readable text',
    category: 'Text & Analysis',
    keywords: ['cron', 'schedule', 'explain', 'human', 'text'],
  },
   {
     id: 'json-path',
     name: 'JSON Path Evaluator',
     description: 'Query JSON with JSONPath expressions',
     category: 'Text & Analysis',
     keywords: ['json', 'path', 'jsonpath', 'query', 'evaluate'],
   },
   {
     id: 'json-jq',
     name: 'JSON Query (JQ)',
     description: 'Query JSON with jq-like syntax',
     category: 'Text & Analysis',
     keywords: ['json', 'jq', 'query', 'filter', 'select'],
   },
  {
    id: 'url-parser',
    name: 'URL Parser',
    description: 'Parse and analyze URL components',
    category: 'Text & Analysis',
    keywords: ['url', 'parse', 'analyze', 'components', 'query', 'path'],
  },
  {
    id: 'html-markdown',
    name: 'HTML → Markdown',
    description: 'Convert HTML to Markdown format',
    category: 'Text & Analysis',
    keywords: ['html', 'markdown', 'convert', 'md'],
  },
  {
    id: 'text-slug',
    name: 'Text to Slug',
    description: 'Convert text to URL-friendly slugs',
    category: 'Text & Analysis',
    keywords: ['slug', 'url', 'friendly', 'convert', 'text', 'seo'],
  },
  {
    id: 'string-escape',
    name: 'String Escape/Unescape',
    description: 'Escape and unescape strings for various languages',
    category: 'Text & Analysis',
    keywords: ['escape', 'unescape', 'string', 'json', 'javascript', 'sql'],
  },
  {
     id: 'extract-emails-urls',
     name: 'Extract Emails/URLs',
     description: 'Extract all email addresses or URLs from text',
     category: 'Text & Analysis',
     keywords: ['extract', 'email', 'url', 'find', 'parse', 'links'],
   },
  {
      id: 'find-replace',
      name: 'Find & Replace',
      description: 'Advanced find and replace with regex support',
      category: 'Text & Analysis',
      keywords: ['find', 'replace', 'search', 'regex', 'pattern', 'substitute'],
  },

  // Generators
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate random UUIDs (v4) or timestamp-based UUIDs',
    category: 'Generators',
    keywords: ['uuid', 'guid', 'generate', 'random', 'unique', 'identifier', 'v4', 'v1'],
  },
  {
    id: 'password', // Short ID for legacy
    name: 'Password Generator',
    description: 'Generate secure random passwords with configurable options',
    category: 'Generators',
    keywords: ['password', 'generate', 'random', 'secure', 'strong'],
  },
  {
    id: 'lorem',
    name: 'Lorem Ipsum Generator',
    description: 'Generate placeholder Lorem Ipsum text',
    category: 'Generators',
    keywords: ['lorem', 'ipsum', 'placeholder', 'text', 'generate', 'dummy'],
  },
  {
    id: 'qrcode',
    name: 'QR Code Generator',
    description: 'Generate QR codes from text or URLs',
    category: 'Generators',
    keywords: ['qr', 'qrcode', 'code', 'generate', 'barcode'],
  },
  {
    id: 'markdown-table-generator',
    name: 'Markdown Table Generator',
    description: 'Create and edit Markdown tables visually',
    category: 'Generators',
    keywords: ['markdown', 'table', 'grid', 'visual', 'editor'],
  },
  {
    id: 'meta-tag-generator',
    name: 'Meta Tag Generator',
    description: 'Generate SEO and Social Media (Open Graph, Twitter) meta tags',
    category: 'Generators',
    keywords: ['meta', 'seo', 'tags', 'open graph', 'social', 'generator'],
  },
  {
    id: 'gitignore-generator',
    name: '.gitignore Generator',
    description: 'Generate .gitignore files for various languages and frameworks',
    category: 'Generators',
    keywords: ['gitignore', 'git', 'ignore', 'generate', 'template', 'language', 'framework'],
  },
  {
    id: 'color-palette',
    name: 'Color Palette Generator',
    description: 'Generate harmonious color palettes',
    category: 'Generators',
    keywords: ['color', 'palette', 'generate', 'harmonious', 'scheme'],
  },
  {
    id: 'box-shadow-generator',
    name: 'Box-Shadow Generator',
    description: 'Generate CSS box-shadow visually',
    category: 'Generators',
    keywords: ['box-shadow', 'css', 'shadow', 'generate', 'visual', 'styling'],
  },
  {
    id: 'glassmorphism-generator',
    name: 'Glassmorphism Generator',
    description: 'Generate CSS for the frosted glass effect',
    category: 'Generators',
    keywords: ['css', 'glassmorphism', 'glass', 'blur', 'transparency', 'generator'],
  },
  {
    id: 'clip-path-generator',
    name: 'CSS Clip Path Generator',
    description: 'Create complex CSS shapes visually with interactive polygons',
    category: 'Generators',
    keywords: ['css', 'clip-path', 'polygon', 'shape', 'generator', 'visual'],
  },
  {
    id: 'triangle-generator',
    name: 'CSS Triangle Generator',
    description: 'Generate pure CSS triangles using boders',
    category: 'Generators',
    keywords: ['css', 'triangle', 'shape', 'border', 'generator'],
  },
  {
    id: 'code-to-image',
    name: 'Code to Image',
    description: 'Create beautiful code screenshots for social media',
    category: 'Generators',
    keywords: ['code', 'image', 'screenshot', 'carbon', 'share', 'snippet'],
  },
  {
    id: 'json-to-zod',
    name: 'JSON to Zod Schema',
    description: 'Generate Zod schemas (TypeScript) from JSON objects',
    category: 'Generators',
    keywords: ['json', 'zod', 'schema', 'typescript', 'generate', 'validation'],
  },
  {
    id: 'readme-generator',
    name: 'README Generator',
    description: 'Generate README.md files with templates',
    category: 'Generators',
    keywords: ['readme', 'markdown', 'generate', 'template', 'documentation', 'md'],
  },

  // DevOps & Network
  {
    id: 'docker-converter',
    name: 'Docker Run → Compose',
    description: 'Convert "docker run" commands to docker-compose.yml',
    category: 'DevOps & Network',
    keywords: ['docker', 'compose', 'convert', 'yaml', 'container'],
  },
  {
    id: 'nginx-generator',
    name: 'Nginx Config Generator',
    description: 'Generate common Nginx server blocks (Proxy, SPA, Static)',
    category: 'DevOps & Network',
    keywords: ['nginx', 'config', 'server', 'proxy', 'generate'],
  },
  {
    id: 'cidr-calculator',
    name: 'CIDR Calculator',
    description: 'Calculate IP address ranges from CIDR notation',
    category: 'DevOps & Network',
    keywords: ['cidr', 'ip', 'subnet', 'network', 'calculator', 'address range'],
  },
  {
    id: 'unix-permissions',
    name: 'Unix Permissions (Chmod)',
    description: 'Calculate chmod values and visualize file permissions',
    category: 'DevOps & Network',
    keywords: ['unix', 'permissions', 'chmod', 'file', 'rwx', 'octal'],
  },
  {
      id: 'http-status',
      name: 'HTTP Status Code Reference',
      description: 'Quick reference for HTTP status codes with descriptions and use cases',
      category: 'DevOps & Network',
      keywords: ['http', 'status', 'code', 'reference', 'error', 'response'],
  },
  {
      id: 'user-agent',
      name: 'User Agent Parser',
      description: 'Decode and analyze user agent strings',
      category: 'DevOps & Network',
      keywords: ['user agent', 'parser', 'browser', 'os', 'device', 'analyze'],
  },

  // Security & Crypto
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and inspect JSON Web Tokens (header & payload)',
    category: 'Security & Crypto',
    keywords: ['jwt', 'token', 'decode', 'json', 'web', 'auth', 'header', 'payload'],
  },
  {
    id: 'hash',
    name: 'Hash Generator',
    description: 'Generate SHA-256, SHA-512, SHA-1 hash values',
    category: 'Security & Crypto',
    keywords: ['hash', 'sha256', 'sha512', 'sha1', 'md5', 'checksum'],
  },
  {
    id: 'hmac',
    name: 'HMAC Generator',
    description: 'Generate HMAC signatures with various algorithms',
    category: 'Security & Crypto',
    keywords: ['hmac', 'hash', 'mac', 'signature', 'secret', 'key'],
  },
  {
    id: 'bcrypt',
    name: 'Bcrypt Hash Generator',
    description: 'Generate bcrypt password hashes',
    category: 'Security & Crypto',
    keywords: ['bcrypt', 'hash', 'password', 'generate', 'security'],
  },
  {
    id: 'password-strength',
    name: 'Password Strength checker',
    description: 'Analyze password strength and entropy',
    category: 'Security & Crypto',
    keywords: ['password', 'strength', 'checker', 'security', 'entropy', 'analyze'],
  },
  {
    id: 'rsa',
    name: 'RSA Key Generator',
    description: 'Generate RSA public/private key pairs',
    category: 'Security & Crypto',
    keywords: ['rsa', 'key', 'generate', 'public', 'private', 'crypto'],
  },
  {
    id: 'cors',
    name: 'CORS Header Generator',
    description: 'Generate CORS headers for APIs',
    category: 'Security & Crypto',
    keywords: ['cors', 'header', 'generate', 'api', 'cross-origin'],
  },
  {
    id: 'website-security',
    name: 'Website Security Checker',
    description: 'Analyze website security with URL checks and external tool recommendations',
    category: 'Security & Crypto',
    keywords: ['security', 'website', 'ssl', 'https', 'checker', 'scan', 'vulnerability'],
  },

  // Cheatsheets
  {
    id: 'git-explorer', // Replacing git-cheat with more interactive version if possible, or keeping both
    name: 'Git Cheatsheet Explorer',
    description: 'Interactive Git command explorer',
    category: 'Cheatsheets',
    keywords: ['git', 'cheat sheet', 'command', 'undo', 'branch', 'merge'],
  },
  {
     id: 'linux-commands',
     name: 'Linux Commands Cheat Sheet',
     description: 'Common Linux commands reference',
     category: 'Cheatsheets',
     keywords: ['linux', 'commands', 'cheat sheet', 'reference', 'terminal', 'bash'],
  },
   {
     id: 'regex-cheat',
     name: 'Regex Cheat Sheet',
     description: 'Quick reference for regular expression syntax',
     category: 'Cheatsheets',
     keywords: ['regex', 'regular expression', 'cheat sheet', 'reference', 'pattern'],
   },
  {
     id: 'http-methods',
     name: 'HTTP Methods Reference',
     description: 'Reference for HTTP methods (GET, POST, PUT, DELETE, etc.)',
     category: 'Cheatsheets',
     keywords: ['http', 'methods', 'get', 'post', 'put', 'delete', 'reference'],
  },
  {
     id: 'keyboard-codes',
     name: 'Keyboard Event Codes Reference',
     description: 'Reference for JavaScript keyboard event codes with interactive testing',
     category: 'Cheatsheets',
     keywords: ['keyboard', 'event', 'keycode', 'key', 'javascript', 'reference'],
  },
  {
    id: 'iban-validator',
    name: 'IBAN Validator',
    description: 'Validate and parse International Bank Account Numbers',
    category: 'Converters & Formatters',
    keywords: ['iban', 'bank', 'validate', 'check', 'finance'],
  },

  // AI
  {
    id: 'token-counter',
    name: 'AI Token Counter',
    description: 'Count tokens and estimate costs for GPT, Claude, and other models',
    category: 'AI',
    keywords: ['ai', 'token', 'count', 'cost', 'gpt', 'claude', 'llm'],
  },
  {
    id: 'prompt-template',
    name: 'Prompt Template Generator',
    description: 'Create and manage reusable AI prompt templates with variables',
    category: 'AI',
    keywords: ['ai', 'prompt', 'template', 'generator', 'llm'],
  },
  {
    id: 'ai-response-formatter',
    name: 'AI Response Formatter',
    description: 'Extract and clean code blocks from AI responses',
    category: 'AI',
    keywords: ['ai', 'response', 'format', 'code', 'extract', 'clean'],
  },
  {
    id: 'prompt-helper',
    name: 'Prompt Engineering Helper',
    description: 'Build structured prompts with role, context, task, and format',
    category: 'AI',
    keywords: ['ai', 'prompt', 'engineering', 'structure', 'helper'],
  },
  {
    id: 'model-comparison',
    name: 'AI Model Comparison',
    description: 'Compare specs, pricing, and features of different AI models',
    category: 'AI',
    keywords: ['ai', 'model', 'comparison', 'pricing', 'specs', 'gpt', 'claude'],
  },
  {
    id: 'json-schema-ai',
    name: 'JSON Schema for AI',
    description: 'Generate and validate JSON schemas for structured AI outputs',
    category: 'AI',
    keywords: ['ai', 'json', 'schema', 'validate', 'structured', 'output'],
  },
  {
    id: 'few-shot-builder',
    name: 'Few-Shot Example Builder',
    description: 'Create and manage few-shot learning examples for AI prompts',
    category: 'AI',
    keywords: ['ai', 'few-shot', 'examples', 'learning', 'prompt'],
  },
  {
    id: 'ai-safety',
    name: 'AI Safety Checker',
    description: 'Detect prompt injection, PII, and security issues in AI interactions',
    category: 'AI',
    keywords: ['ai', 'safety', 'security', 'pii', 'injection', 'privacy'],
  },
  {
    id: 'aes',
    name: 'Aes Encrypt Decrypt',
    description: 'Encrypt and decrypt text using AES algorithm',
    category: 'Security & Crypto',
    keywords: ['aes', 'encrypt', 'decrypt', 'security'],
  },
  {
    id: 'api-key',
    name: 'Api Key Generator',
    description: 'Generate api key effortlessly',
    category: 'Generators',
    keywords: ['api', 'key', 'generator'],
  },
  {
    id: 'ascii-table',
    name: 'Ascii Table',
    description: 'A versatile tool for ascii table',
    category: 'Cheatsheets',
    keywords: ['ascii', 'table'],
  },
  {
    id: 'aspect-ratio',
    name: 'Aspect Ratio Calculator',
    description: 'A versatile tool for aspect ratio calculator',
    category: 'Generators',
    keywords: ['aspect', 'ratio', 'calculator'],
  },
  {
    id: 'barcode',
    name: 'Barcode Generator',
    description: 'Generate barcode effortlessly',
    category: 'Generators',
    keywords: ['barcode', 'generator'],
  },
  {
    id: 'binary',
    name: 'Binary Text Tool',
    description: 'A versatile tool for binary text tool',
    category: 'Text & Analysis',
    keywords: ['binary', 'text', 'tool'],
  },
  {
    id: 'border-radius',
    name: 'Border Radius Generator',
    description: 'Generate border radius effortlessly',
    category: 'Generators',
    keywords: ['border', 'radius', 'generator'],
  },
  {
    id: 'byte-size',
    name: 'Byte Size Converter',
    description: 'Convert between different byte size formats',
    category: 'Converters & Formatters',
    keywords: ['byte', 'size', 'converter'],
  },
  {
    id: 'color-names',
    name: 'Color Names Reference',
    description: 'Quick reference for color names reference',
    category: 'Cheatsheets',
    keywords: ['color', 'names', 'reference'],
  },
  {
    id: 'cookie-parser',
    name: 'Cookie Parser',
    description: 'A versatile tool for cookie parser',
    category: 'Converters & Formatters',
    keywords: ['cookie', 'parser'],
  },
  {
    id: 'cron-parser',
    name: 'Cron Expression Parser',
    description: 'A versatile tool for cron expression parser',
    category: 'Converters & Formatters',
    keywords: ['cron', 'expression', 'parser'],
  },
  {
    id: 'crontab',
    name: 'Crontab Generator',
    description: 'Generate crontab effortlessly',
    category: 'Generators',
    keywords: ['crontab', 'generator'],
  },
  {
    id: 'csp',
    name: 'Csp Header Generator',
    description: 'Generate csp header effortlessly',
    category: 'Generators',
    keywords: ['csp', 'header', 'generator'],
  },
  {
    id: 'css-grid',
    name: 'CSS Grid Generator',
    description: 'Generate css grid effortlessly',
    category: 'Generators',
    keywords: ['css', 'grid', 'generator'],
  },
  {
    id: 'css-units',
    name: 'CSS Units Reference',
    description: 'Quick reference for css units reference',
    category: 'Cheatsheets',
    keywords: ['css', 'units', 'reference'],
  },
  {
    id: 'csv-markdown',
    name: 'Csv To Markdown Table',
    description: 'A versatile tool for csv to markdown table',
    category: 'Converters & Formatters',
    keywords: ['csv', 'markdown', 'table'],
  },
  {
    id: 'curl',
    name: 'Curl Converter',
    description: 'Convert between different curl formats',
    category: 'Converters & Formatters',
    keywords: ['curl', 'converter'],
  },
  {
    id: 'dataurl',
    name: 'Data URL Tool',
    description: 'A versatile tool for data url tool',
    category: 'DevOps & Network',
    keywords: ['data', 'url', 'tool'],
  },
  {
    id: 'duplicate-lines',
    name: 'Duplicate Remover',
    description: 'A versatile tool for duplicate remover',
    category: 'Text & Analysis',
    keywords: ['duplicate', 'remover'],
  },
  {
    id: 'emoji-picker',
    name: 'Emoji Picker',
    description: 'A versatile tool for emoji picker',
    category: 'DevOps & Network',
    keywords: ['emoji', 'picker'],
  },
  {
    id: 'env-formatter',
    name: 'Env Formatter',
    description: 'Format and beautify env code',
    category: 'Converters & Formatters',
    keywords: ['env', 'formatter'],
  },
  {
    id: 'epoch',
    name: 'Epoch Converter',
    description: 'Convert between different epoch formats',
    category: 'Converters & Formatters',
    keywords: ['epoch', 'converter'],
  },
  {
    id: 'fake-data',
    name: 'Fake Data Generator',
    description: 'Generate fake data effortlessly',
    category: 'Generators',
    keywords: ['fake', 'data', 'generator'],
  },
  {
    id: 'favicon',
    name: 'Favicon Generator',
    description: 'Generate favicon effortlessly',
    category: 'Generators',
    keywords: ['favicon', 'generator'],
  },
  {
    id: 'flexbox',
    name: 'Flexbox Playground',
    description: 'A versatile tool for flexbox playground',
    category: 'Generators',
    keywords: ['flexbox', 'playground'],
  },
  {
    id: 'git-cheat',
    name: 'Git Cheat Sheet',
    description: 'Quick reference for git cheat sheet',
    category: 'DevOps & Network',
    keywords: ['git', 'cheat', 'sheet'],
  },
  {
    id: 'gradient',
    name: 'Gradient Generator',
    description: 'Generate gradient effortlessly',
    category: 'Generators',
    keywords: ['gradient', 'generator'],
  },
  {
    id: 'graphql-formatter',
    name: 'Graph QLFormatter',
    description: 'Format and beautify graph qlformatter code',
    category: 'Converters & Formatters',
    keywords: ['graph', 'qlformatter'],
  },
  {
    id: 'hex',
    name: 'Hex Ascii Tool',
    description: 'A versatile tool for hex ascii tool',
    category: 'Text & Analysis',
    keywords: ['hex', 'ascii', 'tool'],
  },
  {
    id: 'htaccess',
    name: 'Htaccess Generator',
    description: 'Generate htaccess effortlessly',
    category: 'Generators',
    keywords: ['htaccess', 'generator'],
  },
  {
    id: 'html-entities',
    name: 'HTML Entities Reference',
    description: 'Quick reference for html entities reference',
    category: 'Cheatsheets',
    keywords: ['html', 'entities', 'reference'],
  },
  {
    id: 'http-header-parser',
    name: 'Http Header Parser',
    description: 'A versatile tool for http header parser',
    category: 'Converters & Formatters',
    keywords: ['http', 'header', 'parser'],
  },
  {
    id: 'json-diff',
    name: 'Json Diff',
    description: 'A versatile tool for json diff',
    category: 'Converters & Formatters',
    keywords: ['json', 'diff'],
  },
  {
    id: 'json-minify',
    name: 'Json Minifier',
    description: 'A versatile tool for json minifier',
    category: 'Converters & Formatters',
    keywords: ['json', 'minifier'],
  },
  {
    id: 'json-schema',
    name: 'Json Schema Validator',
    description: 'A versatile tool for json schema validator',
    category: 'Converters & Formatters',
    keywords: ['json', 'schema', 'validator'],
  },
  {
    id: 'json-tree',
    name: 'Json Tree Viewer',
    description: 'A versatile tool for json tree viewer',
    category: 'Converters & Formatters',
    keywords: ['json', 'tree', 'viewer'],
  },
  {
    id: 'jwt-generator',
    name: 'JWT Generator',
    description: 'Generate jwt effortlessly',
    category: 'Generators',
    keywords: ['jwt', 'generator'],
  },
  {
    id: 'keyboard-shortcuts',
    name: 'Keyboard Shortcuts',
    description: 'A versatile tool for keyboard shortcuts',
    category: 'Cheatsheets',
    keywords: ['keyboard', 'shortcuts'],
  },
  {
    id: 'length',
    name: 'Length Converter',
    description: 'Convert between different length formats',
    category: 'Converters & Formatters',
    keywords: ['length', 'converter'],
  },
  {
    id: 'license',
    name: 'License Generator',
    description: 'Generate license effortlessly',
    category: 'Generators',
    keywords: ['license', 'generator'],
  },
  {
    id: 'line-numbers',
    name: 'Line Numbers',
    description: 'A versatile tool for line numbers',
    category: 'Generators',
    keywords: ['line', 'numbers'],
  },
  {
    id: 'line-sort',
    name: 'Line Sorter',
    description: 'A versatile tool for line sorter',
    category: 'Text & Analysis',
    keywords: ['line', 'sorter'],
  },
  {
    id: 'lorem-picsum',
    name: 'Lorem Picsum URLs',
    description: 'Generate placeholder image URLs from Picsum Photos',
    category: 'Generators',
    keywords: ['lorem', 'picsum', 'urls'],
  },
  {
    id: 'markdown-formatter',
    name: 'Markdown Formatter',
    description: 'Format and beautify markdown code',
    category: 'Converters & Formatters',
    keywords: ['markdown', 'formatter'],
  },
  {
    id: 'markdown-table',
    name: 'Markdown Table Generator',
    description: 'Generate markdown table effortlessly',
    category: 'Generators',
    keywords: ['markdown', 'table', 'generator'],
  },
  {
    id: 'markdown',
    name: 'Markdown Preview',
    description: 'A versatile tool for markdown preview',
    category: 'Generators',
    keywords: ['markdown', 'preview'],
  },
  {
    id: 'meta-tag',
    name: 'Meta Tag Generator',
    description: 'Generate meta tag effortlessly',
    category: 'Generators',
    keywords: ['meta', 'tag', 'generator'],
  },
  {
    id: 'mime-types',
    name: 'Mime Types Reference',
    description: 'Quick reference for mime types reference',
    category: 'Cheatsheets',
    keywords: ['mime', 'types', 'reference'],
  },
  {
    id: 'mock-json',
    name: 'Mock Json Generator',
    description: 'Generate mock json effortlessly',
    category: 'Converters & Formatters',
    keywords: ['mock', 'json', 'generator'],
  },
  {
    id: 'morse-code',
    name: 'Morse Code Translator',
    description: 'A versatile tool for morse code translator',
    category: 'Generators',
    keywords: ['morse', 'code', 'translator'],
  },
  {
    id: 'nanoid',
    name: 'Nano ID Generator',
    description: 'Generate nano id effortlessly',
    category: 'Generators',
    keywords: ['nano', 'generator', 'nanoid'],
  },
  {
    id: 'nginx-formatter',
    name: 'Nginx Formatter',
    description: 'Format and beautify nginx code',
    category: 'Converters & Formatters',
    keywords: ['nginx', 'formatter'],
  },
  {
    id: 'number-to-words',
    name: 'Number To Words',
    description: 'A versatile tool for number to words',
    category: 'Text & Analysis',
    keywords: ['number', 'words'],
  },
  {
    id: 'open-graph',
    name: 'Open Graph Preview',
    description: 'A versatile tool for open graph preview',
    category: 'Generators',
    keywords: ['open', 'graph', 'preview'],
  },
  {
    id: 'php-formatter',
    name: 'Php Formatter',
    description: 'Format and beautify php code',
    category: 'Converters & Formatters',
    keywords: ['php', 'formatter'],
  },
  {
    id: 'placeholder-image',
    name: 'Placeholder Image Generator',
    description: 'Generate placeholder image effortlessly',
    category: 'Generators',
    keywords: ['placeholder', 'image', 'generator'],
  },
  {
    id: 'properties-json',
    name: 'Properties Json Converter',
    description: 'Convert between different properties json formats',
    category: 'Converters & Formatters',
    keywords: ['properties', 'json', 'converter'],
  },
  {
    id: 'punycode',
    name: 'Punycode Converter',
    description: 'Convert between different punycode formats',
    category: 'Converters & Formatters',
    keywords: ['punycode', 'converter'],
  },
  {
    id: 'query-string-builder',
    name: 'Query String Builder',
    description: 'A versatile tool for query string builder',
    category: 'Generators',
    keywords: ['query', 'string', 'builder'],
  },
  {
    id: 'random-number',
    name: 'Random Number Generator',
    description: 'Generate random number effortlessly',
    category: 'Generators',
    keywords: ['random', 'number', 'generator'],
  },
  {
    id: 'random-string',
    name: 'Random String Generator',
    description: 'Generate random string effortlessly',
    category: 'Generators',
    keywords: ['random', 'string', 'generator'],
  },
  {
    id: 'regex-generator',
    name: 'Regex Generator',
    description: 'Generate regex effortlessly',
    category: 'Generators',
    keywords: ['regex', 'generator'],
  },
  {
    id: 'robots-txt',
    name: 'Robots Txt Generator',
    description: 'Generate robots txt effortlessly',
    category: 'Generators',
    keywords: ['robots', 'txt', 'generator'],
  },
  {
    id: 'rot13',
    name: 'ROT13Cipher',
    description: 'A versatile tool for rot13cipher',
    category: 'DevOps & Network',
    keywords: ['rot13'],
  },
  {
    id: 'shell-formatter',
    name: 'Shell Formatter',
    description: 'Format and beautify shell code',
    category: 'Converters & Formatters',
    keywords: ['shell', 'formatter'],
  },
  {
    id: 'shuffle-lines',
    name: 'Shuffle Lines',
    description: 'A versatile tool for shuffle lines',
    category: 'Text & Analysis',
    keywords: ['shuffle', 'lines'],
  },
  {
    id: 'sitemap',
    name: 'Sitemap Generator',
    description: 'Generate sitemap effortlessly',
    category: 'Generators',
    keywords: ['sitemap', 'generator'],
  },
  {
    id: 'sql-insert',
    name: 'SQL Insert Generator',
    description: 'Generate sql insert effortlessly',
    category: 'Generators',
    keywords: ['sql', 'insert', 'generator'],
  },
  {
    id: 'sri',
    name: 'Sri Generator',
    description: 'Generate sri effortlessly',
    category: 'Generators',
    keywords: ['sri', 'generator'],
  },
  {
    id: 'ssl-certificate',
    name: 'Ssl Certificate Decoder',
    description: 'A versatile tool for ssl certificate decoder',
    category: 'Security & Crypto',
    keywords: ['ssl', 'certificate', 'decoder'],
  },
  {
    id: 'string-reverse',
    name: 'String Reverse',
    description: 'A versatile tool for string reverse',
    category: 'Text & Analysis',
    keywords: ['string', 'reverse'],
  },
  {
    id: 'svg-optimizer',
    name: 'Svg Optimizer',
    description: 'A versatile tool for svg optimizer',
    category: 'Generators',
    keywords: ['svg', 'optimizer'],
  },
  {
    id: 'temperature',
    name: 'Temperature Converter',
    description: 'Convert between different temperature formats',
    category: 'Converters & Formatters',
    keywords: ['temperature', 'converter'],
  },
  {
    id: 'text-ascii-art',
    name: 'Text Ascii Art',
    description: 'A versatile tool for text ascii art',
    category: 'Text & Analysis',
    keywords: ['text', 'ascii', 'art'],
  },
  {
    id: 'text-repeater',
    name: 'Text Repeater',
    description: 'A versatile tool for text repeater',
    category: 'Text & Analysis',
    keywords: ['text', 'repeater'],
  },
  {
    id: 'text-truncator',
    name: 'Text Truncator',
    description: 'A versatile tool for text truncator',
    category: 'Text & Analysis',
    keywords: ['text', 'truncator'],
  },
  {
    id: 'text',
    name: 'Regex Visualizer',
    description: 'A versatile tool for regex visualizer',
    category: 'Text & Analysis',
    keywords: ['regex', 'visualizer'],
  },
  {
    id: 'timezone',
    name: 'Timezone Converter',
    description: 'Convert between different timezone formats',
    category: 'Converters & Formatters',
    keywords: ['timezone', 'converter'],
  },
  {
    id: 'toml-formatter',
    name: 'Toml Formatter',
    description: 'Format and beautify toml code',
    category: 'Converters & Formatters',
    keywords: ['toml', 'formatter'],
  },
  {
    id: 'toml-json',
    name: 'Toml Json Converter',
    description: 'Convert between different toml json formats',
    category: 'Converters & Formatters',
    keywords: ['toml', 'json', 'converter'],
  },
  {
    id: 'tsv-csv',
    name: 'Tsv Csv Converter',
    description: 'Convert between different tsv csv formats',
    category: 'Converters & Formatters',
    keywords: ['tsv', 'csv', 'converter'],
  },
  {
    id: 'ulid',
    name: 'Ulid Generator',
    description: 'Generate ulid effortlessly',
    category: 'Generators',
    keywords: ['ulid', 'generator'],
  },
  {
    id: 'unicode-escape',
    name: 'Unicode Escape',
    description: 'A versatile tool for unicode escape',
    category: 'Generators',
    keywords: ['unicode', 'escape'],
  },
  {
    id: 'unicode-search',
    name: 'Unicode Character Search',
    description: 'A versatile tool for unicode character search',
    category: 'Generators',
    keywords: ['unicode', 'character', 'search'],
  },
  {
    id: 'vim-cheat',
    name: 'Vim Cheat Sheet',
    description: 'Quick reference for vim cheat sheet',
    category: 'Cheatsheets',
    keywords: ['vim', 'cheat', 'sheet'],
  },
  {
    id: 'weight',
    name: 'Weight Converter',
    description: 'Convert between different weight formats',
    category: 'Converters & Formatters',
    keywords: ['weight', 'converter'],
  },
  {
    id: 'whitespace-remover',
    name: 'Whitespace Remover',
    description: 'A versatile tool for whitespace remover',
    category: 'Text & Analysis',
    keywords: ['whitespace', 'remover'],
  },
],

export const categories = [
  'Converters & Formatters',
  'Text & Analysis',
  'Generators',
  'DevOps & Network',
  'Security & Crypto',
  'Cheatsheets',
  'AI'
] as ToolCategory[]

export function getToolDefinitionById(id: string): ToolDefinition | undefined {
  return toolDefinitions.find((t) => t.id === id)
}
