import { ToolCategory } from './types'

export interface ToolDefinition {
  id: string
  name: string
  description: string
  category: ToolCategory
  keywords: string[]
}

export const toolDefinitions: ToolDefinition[] = [
  // JSON Tools
  {
    id: 'json-formatter',
    name: 'JSON Formatter & Validator',
    description: 'Format, validate, and beautify JSON data with syntax highlighting',
    category: 'JSON',
    keywords: ['json', 'format', 'validate', 'beautify', 'minify', 'parse'],
  },
  {
    id: 'json-yaml',
    name: 'JSON ↔ YAML Converter',
    description: 'Convert between JSON and YAML formats',
    category: 'Converter',
    keywords: ['json', 'yaml', 'convert', 'transform', 'config'],
  },
  {
    id: 'json-diff',
    name: 'JSON Diff/Compare',
    description: 'Compare two JSON documents and highlight differences',
    category: 'JSON',
    keywords: ['json', 'diff', 'compare', 'difference', 'merge'],
  },
  {
    id: 'json-csv',
    name: 'JSON ↔ CSV Converter',
    description: 'Convert JSON arrays to CSV and CSV to JSON',
    category: 'Converter',
    keywords: ['json', 'csv', 'convert', 'export', 'import', 'spreadsheet'],
  },
  {
    id: 'json-minify',
    name: 'JSON Minifier',
    description: 'Minify JSON by removing whitespace',
    category: 'JSON',
    keywords: ['json', 'minify', 'compress', 'compact', 'size'],
  },
  {
    id: 'json-typescript',
    name: 'JSON to TypeScript',
    description: 'Generate TypeScript interfaces from JSON',
    category: 'JSON',
    keywords: ['json', 'typescript', 'interface', 'generate', 'type'],
  },
  {
    id: 'json-path',
    name: 'JSON Path Evaluator',
    description: 'Query JSON with JSONPath expressions',
    category: 'JSON',
    keywords: ['json', 'path', 'jsonpath', 'query', 'evaluate'],
  },
  {
    id: 'json-tree',
    name: 'JSON Tree Viewer',
    description: 'Interactive tree visualization of JSON',
    category: 'JSON',
    keywords: ['json', 'tree', 'viewer', 'visualize', 'browse'],
  },
  {
    id: 'json-go',
    name: 'JSON to Go Struct',
    description: 'Generate Go structs from JSON',
    category: 'JSON',
    keywords: ['json', 'go', 'golang', 'struct', 'generate'],
  },
  {
    id: 'json-rust',
    name: 'JSON to Rust Struct',
    description: 'Generate Rust structs from JSON',
    category: 'JSON',
    keywords: ['json', 'rust', 'struct', 'generate', 'serde'],
  },
  {
    id: 'json-jq',
    name: 'JSON Query (JQ)',
    description: 'Query JSON with jq-like syntax',
    category: 'JSON',
    keywords: ['json', 'jq', 'query', 'filter', 'select'],
  },
  {
    id: 'json-schema',
    name: 'JSON Schema Validator',
    description: 'Validate JSON against a JSON Schema',
    category: 'JSON',
    keywords: ['json', 'schema', 'validate', 'validation'],
  },
  {
    id: 'mock-json',
    name: 'Mock JSON Generator',
    description: 'Generate mock JSON from schema',
    category: 'Generator',
    keywords: ['mock', 'json', 'generate', 'data', 'test', 'schema'],
  },

  // Encoding Tools
  {
    id: 'base64',
    name: 'Base64 Encode / Decode',
    description: 'Encode text to Base64 or decode Base64 strings',
    category: 'Encoding',
    keywords: ['base64', 'encode', 'decode', 'convert', 'binary'],
  },
  {
    id: 'url-encode',
    name: 'URL Encode / Decode',
    description: 'Encode or decode URL components and query strings',
    category: 'Encoding',
    keywords: ['url', 'encode', 'decode', 'uri', 'percent', 'query'],
  },
  {
    id: 'html-entity',
    name: 'HTML Entity Encode/Decode',
    description: 'Convert special characters to HTML entities and vice versa',
    category: 'Encoding',
    keywords: ['html', 'entity', 'encode', 'decode', 'escape', 'special'],
  },
  {
    id: 'hex-ascii',
    name: 'Hex ↔ ASCII Converter',
    description: 'Convert between hexadecimal and ASCII text',
    category: 'Encoding',
    keywords: ['hex', 'hexadecimal', 'ascii', 'text', 'convert'],
  },
  {
    id: 'binary-text',
    name: 'Binary ↔ Text Converter',
    description: 'Convert between binary and text',
    category: 'Encoding',
    keywords: ['binary', 'text', 'convert', 'bits', 'encode'],
  },
  {
    id: 'dataurl',
    name: 'Data URL Converter',
    description: 'Encode files/text to Data URLs and decode them',
    category: 'Encoding',
    keywords: ['data', 'url', 'base64', 'image', 'file', 'encode'],
  },
  {
    id: 'rot13',
    name: 'ROT13 Cipher',
    description: 'Simple letter substitution cipher (encode/decode)',
    category: 'Encoding',
    keywords: ['rot13', 'cipher', 'encode', 'decode', 'caesar', 'substitution'],
  },
  {
    id: 'unicode-escape',
    name: 'Unicode Escape / Unescape',
    description: 'Convert Unicode characters to escape sequences and vice versa',
    category: 'Encoding',
    keywords: ['unicode', 'escape', 'unescape', 'convert', 'characters'],
  },
  {
    id: 'punycode',
    name: 'Punycode Converter',
    description: 'Convert internationalized domain names to/from punycode',
    category: 'Encoding',
    keywords: ['punycode', 'idn', 'domain', 'convert', 'internationalized'],
  },
  {
    id: 'url-parser',
    name: 'URL Parser',
    description: 'Parse and analyze URL components',
    category: 'Encoding',
    keywords: ['url', 'parse', 'analyze', 'components', 'query', 'path'],
  },
  {
    id: 'query-string-builder',
    name: 'Query String Builder',
    description: 'Build and edit URL query strings',
    category: 'Encoding',
    keywords: ['query', 'string', 'builder', 'url', 'parameters'],
  },
  {
    id: 'morse-code',
    name: 'Morse Code Translator',
    description: 'Convert text to Morse code and back',
    category: 'Encoding',
    keywords: ['morse', 'code', 'translate', 'convert', 'dots', 'dashes'],
  },

  // Text Tools
  {
    id: 'case-converter',
    name: 'Case Converter',
    description: 'Convert text between camelCase, PascalCase, snake_case, and kebab-case',
    category: 'Text',
    keywords: ['case', 'camel', 'pascal', 'snake', 'kebab', 'convert', 'text'],
  },
  {
    id: 'lorem',
    name: 'Lorem Ipsum Generator',
    description: 'Generate placeholder Lorem Ipsum text',
    category: 'Text',
    keywords: ['lorem', 'ipsum', 'placeholder', 'text', 'generate', 'dummy'],
  },
  {
    id: 'word-count',
    name: 'Word & Character Counter',
    description: 'Count words, characters, sentences, and paragraphs',
    category: 'Text',
    keywords: ['word', 'character', 'count', 'sentence', 'paragraph', 'length'],
  },
  {
    id: 'regex',
    name: 'Regex Tester',
    description: 'Test regular expressions with live matching and highlighting',
    category: 'Text',
    keywords: ['regex', 'regular', 'expression', 'test', 'match', 'pattern'],
  },
  {
    id: 'text-diff',
    name: 'Text Diff/Compare',
    description: 'Compare two text inputs and show differences',
    category: 'Text',
    keywords: ['diff', 'compare', 'text', 'difference', 'merge'],
  },
  {
    id: 'markdown',
    name: 'Markdown Preview',
    description: 'Live Markdown preview with GitHub Flavored Markdown support',
    category: 'Text',
    keywords: ['markdown', 'preview', 'md', 'github', 'render'],
  },
  {
    id: 'string-escape',
    name: 'String Escape/Unescape',
    description: 'Escape and unescape strings for various languages',
    category: 'Text',
    keywords: ['escape', 'unescape', 'string', 'json', 'javascript', 'sql'],
  },
  {
    id: 'line-sort',
    name: 'Line Sorter',
    description: 'Sort lines of text alphabetically, numerically, or naturally',
    category: 'Text',
    keywords: ['sort', 'line', 'alphabetical', 'order', 'arrange'],
  },
  {
    id: 'duplicate-lines',
    name: 'Remove Duplicate Lines',
    description: 'Remove duplicate lines from text',
    category: 'Text',
    keywords: ['duplicate', 'remove', 'unique', 'line', 'dedupe'],
  },
  {
    id: 'text-slug',
    name: 'Text to Slug',
    description: 'Convert text to URL-friendly slugs',
    category: 'Text',
    keywords: ['slug', 'url', 'friendly', 'convert', 'text', 'seo'],
  },
  {
    id: 'string-reverse',
    name: 'String Reverse',
    description: 'Reverse text characters, words, or lines',
    category: 'Text',
    keywords: ['reverse', 'string', 'text', 'characters', 'words', 'lines'],
  },
  {
    id: 'text-repeater',
    name: 'Text Repeater',
    description: 'Repeat text n times with customizable separators',
    category: 'Text',
    keywords: ['repeat', 'text', 'duplicate', 'multiply', 'separator'],
  },
  {
    id: 'whitespace-remover',
    name: 'Whitespace Remover',
    description: 'Remove extra spaces, tabs, and newlines from text',
    category: 'Text',
    keywords: ['whitespace', 'remove', 'spaces', 'tabs', 'newlines', 'clean'],
  },
  {
    id: 'line-numbers',
    name: 'Add/Remove Line Numbers',
    description: 'Add or remove line numbers from text',
    category: 'Text',
    keywords: ['line', 'numbers', 'add', 'remove', 'format'],
  },
  {
    id: 'shuffle-lines',
    name: 'Shuffle Lines',
    description: 'Randomly shuffle lines of text',
    category: 'Text',
    keywords: ['shuffle', 'random', 'lines', 'order', 'mix'],
  },
  {
    id: 'extract-emails-urls',
    name: 'Extract Emails/URLs',
    description: 'Extract all email addresses or URLs from text',
    category: 'Text',
    keywords: ['extract', 'email', 'url', 'find', 'parse', 'links'],
  },
  {
    id: 'text-truncator',
    name: 'Text Truncator',
    description: 'Truncate text with ellipsis options',
    category: 'Text',
    keywords: ['truncate', 'text', 'ellipsis', 'cut', 'shorten'],
  },
  {
    id: 'find-replace',
    name: 'Find & Replace',
    description: 'Advanced find and replace with regex support',
    category: 'Text',
    keywords: ['find', 'replace', 'search', 'regex', 'pattern', 'substitute'],
  },
  {
    id: 'number-to-words',
    name: 'Number to Words',
    description: 'Convert numbers to written words',
    category: 'Text',
    keywords: ['number', 'words', 'convert', 'text', 'spell'],
  },
  {
    id: 'text-ascii-art',
    name: 'Text to ASCII Art',
    description: 'Convert text to ASCII art',
    category: 'Text',
    keywords: ['ascii', 'art', 'text', 'convert', 'banner'],
  },

  // Security Tools
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and inspect JSON Web Tokens (header & payload)',
    category: 'Security',
    keywords: ['jwt', 'token', 'decode', 'json', 'web', 'auth', 'header', 'payload'],
  },
  {
    id: 'hash',
    name: 'Hash Generator',
    description: 'Generate SHA-256, SHA-512, SHA-1 hash values',
    category: 'Security',
    keywords: ['hash', 'sha256', 'sha512', 'sha1', 'md5', 'checksum'],
  },
  {
    id: 'hmac',
    name: 'HMAC Generator',
    description: 'Generate HMAC signatures with various algorithms',
    category: 'Security',
    keywords: ['hmac', 'hash', 'mac', 'signature', 'secret', 'key'],
  },
  {
    id: 'password-strength',
    name: 'Password Strength Checker',
    description: 'Analyze password strength and entropy',
    category: 'Security',
    keywords: ['password', 'strength', 'checker', 'security', 'entropy', 'analyze'],
  },
  {
    id: 'api-key',
    name: 'API Key Generator',
    description: 'Generate random API keys with configurable format and length',
    category: 'Security',
    keywords: ['api', 'key', 'generate', 'random', 'secret', 'token'],
  },
  {
    id: 'sri',
    name: 'Subresource Integrity (SRI)',
    description: 'Generate SRI hashes for scripts/styles',
    category: 'Security',
    keywords: ['sri', 'integrity', 'hash', 'subresource', 'security'],
  },
  {
    id: 'cors',
    name: 'CORS Header Generator',
    description: 'Generate CORS headers for APIs',
    category: 'Security',
    keywords: ['cors', 'header', 'generate', 'api', 'cross-origin'],
  },
  {
    id: 'csp',
    name: 'CSP Header Generator',
    description: 'Generate Content Security Policy headers',
    category: 'Security',
    keywords: ['csp', 'content security policy', 'header', 'generate', 'security'],
  },
  {
    id: 'password-strength',
    name: 'Password Strength Checker',
    description: 'Check password strength and get feedback',
    category: 'Security',
    keywords: ['password', 'strength', 'check', 'security', 'validate'],
  },
  {
    id: 'bcrypt',
    name: 'Bcrypt Hash Generator',
    description: 'Generate bcrypt password hashes',
    category: 'Security',
    keywords: ['bcrypt', 'hash', 'password', 'generate', 'security'],
  },
  {
    id: 'aes',
    name: 'AES Encrypt/Decrypt',
    description: 'Encrypt and decrypt data using AES-GCM',
    category: 'Security',
    keywords: ['aes', 'encrypt', 'decrypt', 'crypto', 'security'],
  },
  {
    id: 'rsa',
    name: 'RSA Key Generator',
    description: 'Generate RSA public/private key pairs',
    category: 'Security',
    keywords: ['rsa', 'key', 'generate', 'public', 'private', 'crypto'],
  },
  {
    id: 'ssl-certificate',
    name: 'SSL Certificate Decoder',
    description: 'Decode and parse SSL certificates',
    category: 'Security',
    keywords: ['ssl', 'certificate', 'decode', 'parse', 'tls'],
  },

  // Generator Tools
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate random UUIDs (v4) or timestamp-based UUIDs',
    category: 'Generator',
    keywords: ['uuid', 'guid', 'generate', 'random', 'unique', 'identifier', 'v4', 'v1'],
  },
  {
    id: 'gitignore-generator',
    name: '.gitignore Generator',
    description: 'Generate .gitignore files for various languages and frameworks',
    category: 'Generator',
    keywords: ['gitignore', 'git', 'ignore', 'generate', 'template', 'language', 'framework'],
  },
  {
    id: 'readme-generator',
    name: 'README Generator',
    description: 'Generate README.md files with templates',
    category: 'Generator',
    keywords: ['readme', 'markdown', 'generate', 'template', 'documentation', 'md'],
  },
  {
    id: 'license-generator',
    name: 'LICENSE Generator',
    description: 'Generate license files (MIT, Apache, GPL, etc.)',
    category: 'Generator',
    keywords: ['license', 'mit', 'apache', 'gpl', 'generate', 'legal'],
  },
  {
    id: 'favicon-generator',
    name: 'Favicon Generator',
    description: 'Generate favicon sets from an image',
    category: 'Generator',
    keywords: ['favicon', 'icon', 'generate', 'image', 'apple', 'android', 'chrome'],
  },
  {
    id: 'box-shadow-generator',
    name: 'Box-Shadow Generator',
    description: 'Generate CSS box-shadow visually',
    category: 'Generator',
    keywords: ['box-shadow', 'css', 'shadow', 'generate', 'visual', 'styling'],
  },
  {
    id: 'border-radius-generator',
    name: 'Border-Radius Generator',
    description: 'Generate CSS border-radius visually',
    category: 'Generator',
    keywords: ['border-radius', 'css', 'radius', 'generate', 'visual', 'styling', 'rounded corners'],
  },
  {
    id: 'flexbox-playground',
    name: 'Flexbox Playground',
    description: 'Visual playground for CSS Flexbox',
    category: 'Generator',
    keywords: ['flexbox', 'css', 'flex', 'layout', 'playground', 'visual'],
  },
  {
    id: 'css-grid-generator',
    name: 'CSS Grid Generator',
    description: 'Visual CSS Grid layout generator',
    category: 'Generator',
    keywords: ['css', 'grid', 'layout', 'generate', 'visual', 'template'],
  },
  {
    id: 'password',
    name: 'Password Generator',
    description: 'Generate secure random passwords with configurable options',
    category: 'Generator',
    keywords: ['password', 'generate', 'random', 'secure', 'strong'],
  },
  {
    id: 'qrcode',
    name: 'QR Code Generator',
    description: 'Generate QR codes from text or URLs',
    category: 'Generator',
    keywords: ['qr', 'qrcode', 'code', 'generate', 'barcode'],
  },
  {
    id: 'random-number',
    name: 'Random Number Generator',
    description: 'Generate random numbers with min/max range',
    category: 'Generator',
    keywords: ['random', 'number', 'generate', 'range', 'min', 'max'],
  },
  {
    id: 'random-string',
    name: 'Random String Generator',
    description: 'Generate random strings with custom character sets',
    category: 'Generator',
    keywords: ['random', 'string', 'generate', 'alphanumeric', 'password', 'token'],
  },
  {
    id: 'ulid',
    name: 'ULID Generator',
    description: 'Generate Universally Unique Lexicographically Sortable IDs',
    category: 'Generator',
    keywords: ['ulid', 'generate', 'unique', 'id', 'sortable'],
  },
  {
    id: 'nanoid',
    name: 'NanoID Generator',
    description: 'Generate compact, URL-friendly unique IDs',
    category: 'Generator',
    keywords: ['nanoid', 'generate', 'unique', 'id', 'url', 'friendly'],
  },
  {
    id: 'lorem-picsum',
    name: 'Lorem Picsum URLs',
    description: 'Generate random placeholder image URLs',
    category: 'Generator',
    keywords: ['lorem', 'picsum', 'image', 'placeholder', 'url', 'random'],
  },
  {
    id: 'crontab',
    name: 'Crontab Generator',
    description: 'Build cron expressions visually',
    category: 'Generator',
    keywords: ['crontab', 'cron', 'schedule', 'generate', 'expression'],
  },
  {
    id: 'fake-data',
    name: 'Fake Data Generator',
    description: 'Generate fake names, emails, addresses',
    category: 'Generator',
    keywords: ['fake', 'data', 'generate', 'test', 'mock', 'dummy'],
  },
  {
    id: 'color-palette',
    name: 'Color Palette Generator',
    description: 'Generate harmonious color palettes',
    category: 'Generator',
    keywords: ['color', 'palette', 'generate', 'harmonious', 'scheme'],
  },
  {
    id: 'gradient',
    name: 'Gradient Generator',
    description: 'Create CSS gradients visually',
    category: 'Generator',
    keywords: ['gradient', 'css', 'generate', 'linear', 'radial', 'visual'],
  },
  {
    id: 'sql-insert',
    name: 'SQL INSERT Generator',
    description: 'Generate INSERT statements from data',
    category: 'Generator',
    keywords: ['sql', 'insert', 'generate', 'database', 'query'],
  },
  {
    id: 'regex-generator',
    name: 'Regex Generator',
    description: 'Generate regex from examples',
    category: 'Generator',
    keywords: ['regex', 'generate', 'pattern', 'regular expression'],
  },

  // Web Tools
  {
    id: 'timestamp',
    name: 'Timestamp Converter',
    description: 'Convert between Unix timestamps and human-readable dates',
    category: 'Web',
    keywords: ['timestamp', 'unix', 'date', 'time', 'convert', 'epoch'],
  },
  {
    id: 'color',
    name: 'Color Converter',
    description: 'Convert between HEX, RGB, HSL color formats',
    category: 'Web',
    keywords: ['color', 'hex', 'rgb', 'hsl', 'convert', 'picker'],
  },

  // Formatter Tools
  {
    id: 'html-formatter',
    name: 'HTML Formatter',
    description: 'Format and beautify HTML with proper indentation',
    category: 'Formatter',
    keywords: ['html', 'format', 'beautify', 'indent', 'minify'],
  },
  {
    id: 'css-formatter',
    name: 'CSS Formatter',
    description: 'Format and beautify CSS with proper indentation',
    category: 'Formatter',
    keywords: ['css', 'format', 'beautify', 'indent', 'minify', 'style'],
  },
  {
    id: 'js-formatter',
    name: 'JavaScript Formatter',
    description: 'Format and beautify JavaScript code',
    category: 'Formatter',
    keywords: ['javascript', 'js', 'format', 'beautify', 'indent', 'minify'],
  },
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    description: 'Format and beautify SQL queries',
    category: 'Formatter',
    keywords: ['sql', 'format', 'beautify', 'query', 'database'],
  },
  {
    id: 'xml-formatter',
    name: 'XML Formatter',
    description: 'Format and beautify XML with proper indentation',
    category: 'Formatter',
    keywords: ['xml', 'format', 'beautify', 'indent', 'minify'],
  },

  // Converter Tools
  {
    id: 'number-base',
    name: 'Number Base Converter',
    description: 'Convert numbers between binary, octal, decimal, hexadecimal',
    category: 'Converter',
    keywords: ['number', 'base', 'binary', 'octal', 'decimal', 'hex', 'convert'],
  },
  {
    id: 'byte-size',
    name: 'Byte/Size Converter',
    description: 'Convert between bytes, KB, MB, GB, TB units',
    category: 'Converter',
    keywords: ['byte', 'size', 'kb', 'mb', 'gb', 'tb', 'convert', 'storage'],
  },
  {
    id: 'image-base64',
    name: 'Image to Base64',
    description: 'Convert images to Base64 encoded strings and data URLs',
    category: 'Converter',
    keywords: ['image', 'base64', 'data url', 'convert', 'encode', 'picture'],
  },
  {
    id: 'markdown-html',
    name: 'Markdown → HTML Converter',
    description: 'Convert Markdown to clean HTML',
    category: 'Converter',
    keywords: ['markdown', 'html', 'convert', 'md', 'render'],
  },
  {
    id: 'temperature',
    name: 'Temperature Converter',
    description: 'Convert between Celsius, Fahrenheit, and Kelvin',
    category: 'Converter',
    keywords: ['temperature', 'celsius', 'fahrenheit', 'kelvin', 'convert'],
  },
  {
    id: 'unix-permissions',
    name: 'Unix Permissions (Chmod)',
    description: 'Calculate chmod values and visualize file permissions',
    category: 'Converter',
    keywords: ['unix', 'permissions', 'chmod', 'file', 'rwx', 'octal'],
  },
  {
    id: 'length',
    name: 'Length Converter',
    description: 'Convert between meters, kilometers, inches, feet, yards, miles, etc.',
    category: 'Converter',
    keywords: ['length', 'distance', 'meter', 'kilometer', 'inch', 'foot', 'mile', 'convert'],
  },
  {
    id: 'weight',
    name: 'Weight Converter',
    description: 'Convert between kilograms, grams, pounds, ounces, tons, etc.',
    category: 'Converter',
    keywords: ['weight', 'mass', 'kilogram', 'pound', 'ounce', 'gram', 'convert'],
  },
  {
    id: 'epoch',
    name: 'Epoch Converter',
    description: 'Convert various date formats to Unix epoch timestamp',
    category: 'Converter',
    keywords: ['epoch', 'unix', 'timestamp', 'date', 'convert', 'time'],
  },
  {
    id: 'csv-markdown',
    name: 'CSV → Markdown Table',
    description: 'Convert CSV data to Markdown table format',
    category: 'Converter',
    keywords: ['csv', 'markdown', 'table', 'convert', 'md'],
  },
  {
    id: 'tsv-csv',
    name: 'TSV ↔ CSV Converter',
    description: 'Convert between TSV (Tab-Separated Values) and CSV formats',
    category: 'Converter',
    keywords: ['tsv', 'csv', 'tab', 'separated', 'convert'],
  },
  {
    id: 'xml-json',
    name: 'XML ↔ JSON Converter',
    description: 'Convert between XML and JSON formats',
    category: 'Converter',
    keywords: ['xml', 'json', 'convert', 'transform'],
  },
  {
    id: 'toml-json',
    name: 'TOML ↔ JSON Converter',
    description: 'Convert between TOML and JSON',
    category: 'Converter',
    keywords: ['toml', 'json', 'convert', 'transform'],
  },
  {
    id: 'properties-json',
    name: 'Properties ↔ JSON',
    description: 'Convert Java .properties to JSON',
    category: 'Converter',
    keywords: ['properties', 'json', 'java', 'convert'],
  },
  {
    id: 'image-format',
    name: 'Image Format Converter',
    description: 'Convert between image formats (PNG, JPEG, WebP)',
    category: 'Converter',
    keywords: ['image', 'format', 'convert', 'png', 'jpeg', 'webp'],
  },
  {
    id: 'aspect-ratio',
    name: 'Aspect Ratio Calculator',
    description: 'Calculate aspect ratios and find matching dimensions for images',
    category: 'Converter',
    keywords: ['aspect ratio', 'image ratio', 'dimensions', 'width', 'height', '16:9', '4:3', '1:1', 'calculate', 'resize', 'proportions'],
  },
  {
    id: 'length',
    name: 'Length Converter',
    description: 'Convert between length units',
    category: 'Converter',
    keywords: ['length', 'distance', 'meter', 'kilometer', 'mile', 'inch', 'convert'],
  },
  {
    id: 'weight',
    name: 'Weight Converter',
    description: 'Convert between weight units',
    category: 'Converter',
    keywords: ['weight', 'mass', 'kilogram', 'pound', 'gram', 'convert'],
  },
  {
    id: 'epoch',
    name: 'Epoch Converter',
    description: 'Convert between Unix timestamps and dates',
    category: 'Converter',
    keywords: ['epoch', 'timestamp', 'unix', 'date', 'time', 'convert'],
  },
  {
    id: 'svg-optimizer',
    name: 'SVG Optimizer',
    description: 'Optimize SVG files by removing unnecessary code',
    category: 'Web',
    keywords: ['svg', 'optimize', 'minify', 'compress'],
  },
  {
    id: 'html-markdown',
    name: 'HTML → Markdown',
    description: 'Convert HTML to Markdown format',
    category: 'Converter',
    keywords: ['html', 'markdown', 'convert', 'md'],
  },

  // Formatter Tools (continued)
  {
    id: 'ts-formatter',
    name: 'TypeScript Formatter',
    description: 'Format and beautify TypeScript code',
    category: 'Formatter',
    keywords: ['typescript', 'ts', 'format', 'beautify', 'indent', 'minify'],
  },
  {
    id: 'yaml-formatter',
    name: 'YAML Formatter',
    description: 'Format and beautify YAML with validation',
    category: 'Formatter',
    keywords: ['yaml', 'yml', 'format', 'beautify', 'indent', 'minify'],
  },
  {
    id: 'toml-formatter',
    name: 'TOML Formatter',
    description: 'Format and beautify TOML',
    category: 'Formatter',
    keywords: ['toml', 'format', 'beautify', 'indent'],
  },
  {
    id: 'markdown-formatter',
    name: 'Markdown Formatter',
    description: 'Format and beautify Markdown',
    category: 'Formatter',
    keywords: ['markdown', 'md', 'format', 'beautify'],
  },
  {
    id: 'shell-formatter',
    name: 'Shell/Bash Formatter',
    description: 'Format shell scripts',
    category: 'Formatter',
    keywords: ['shell', 'bash', 'sh', 'format', 'script'],
  },
  {
    id: 'python-formatter',
    name: 'Python Formatter',
    description: 'Format Python code',
    category: 'Formatter',
    keywords: ['python', 'py', 'format', 'beautify'],
  },
  {
    id: 'php-formatter',
    name: 'PHP Formatter',
    description: 'Format PHP code',
    category: 'Formatter',
    keywords: ['php', 'format', 'beautify'],
  },
  {
    id: 'graphql-formatter',
    name: 'GraphQL Formatter',
    description: 'Format GraphQL queries',
    category: 'Formatter',
    keywords: ['graphql', 'gql', 'format', 'query'],
  },

  // Web Tools (continued)
  {
    id: 'http-status',
    name: 'HTTP Status Code Reference',
    description: 'Quick reference for HTTP status codes with descriptions and use cases',
    category: 'Web',
    keywords: ['http', 'status', 'code', 'reference', 'error', 'response'],
  },
  {
    id: 'timezone',
    name: 'Timezone Converter',
    description: 'Convert times between different timezones',
    category: 'Web',
    keywords: ['timezone', 'time', 'convert', 'utc', 'date', 'clock'],
  },
  {
    id: 'cron-parser',
    name: 'Cron Expression Parser',
    description: 'Parse cron expressions to human readable format',
    category: 'Web',
    keywords: ['cron', 'expression', 'parser', 'schedule', 'parse'],
  },
  {
    id: 'http-header-parser',
    name: 'HTTP Header Parser',
    description: 'Parse and analyze HTTP headers',
    category: 'Web',
    keywords: ['http', 'header', 'parse', 'analyze', 'request', 'response'],
  },
  {
    id: 'cookie-parser',
    name: 'Cookie Parser / Builder',
    description: 'Parse and build HTTP cookies',
    category: 'Web',
    keywords: ['cookie', 'parse', 'build', 'http', 'browser'],
  },
  {
    id: 'meta-tag',
    name: 'Meta Tag Generator',
    description: 'Generate meta tags for SEO',
    category: 'Web',
    keywords: ['meta', 'tag', 'seo', 'og', 'open graph', 'twitter', 'generate'],
  },
  {
    id: 'sitemap',
    name: 'Sitemap Generator',
    description: 'Generate XML sitemaps',
    category: 'Web',
    keywords: ['sitemap', 'xml', 'seo', 'generate', 'urls'],
  },
  {
    id: 'robots-txt',
    name: 'Robots.txt Generator',
    description: 'Generate robots.txt files',
    category: 'Web',
    keywords: ['robots', 'txt', 'crawler', 'seo', 'generate'],
  },
  {
    id: 'user-agent',
    name: 'User Agent Parser',
    description: 'Decode and analyze user agent strings',
    category: 'Web',
    keywords: ['user agent', 'parser', 'browser', 'os', 'device', 'analyze'],
  },
  {
    id: 'open-graph',
    name: 'Open Graph Preview',
    description: 'Preview how URLs appear on social media',
    category: 'Web',
    keywords: ['open graph', 'og', 'preview', 'social media', 'meta'],
  },
  {
    id: 'placeholder-image',
    name: 'Placeholder Image Generator',
    description: 'Generate placeholder images',
    category: 'Generator',
    keywords: ['placeholder', 'image', 'generate', 'dummy', 'img'],
  },
  {
    id: 'barcode',
    name: 'Barcode Generator',
    description: 'Generate barcode patterns',
    category: 'Generator',
    keywords: ['barcode', 'generate', 'code128', 'ean13'],
  },

  // Security Tools (continued)
  {
    id: 'jwt-generator',
    name: 'JWT Generator',
    description: 'Generate JSON Web Tokens with custom claims',
    category: 'Security',
    keywords: ['jwt', 'token', 'generate', 'json', 'web', 'auth', 'signature'],
  },

  // Developer Reference Tools
  {
    id: 'ascii-table',
    name: 'ASCII Table Reference',
    description: 'Complete ASCII character reference table',
    category: 'Developer Reference',
    keywords: ['ascii', 'character', 'reference', 'table', 'code', 'decimal', 'hex'],
  },
  {
    id: 'git-cheat',
    name: 'Git Cheat Sheet',
    description: 'Quick reference for common Git commands',
    category: 'Developer Reference',
    keywords: ['git', 'cheat sheet', 'reference', 'commands', 'version control'],
  },
  {
    id: 'regex-cheat',
    name: 'Regex Cheat Sheet',
    description: 'Quick reference for regular expression syntax',
    category: 'Developer Reference',
    keywords: ['regex', 'regular expression', 'cheat sheet', 'reference', 'pattern'],
  },
  {
    id: 'html-entities',
    name: 'HTML Entities Reference',
    description: 'Comprehensive list of HTML entities with names, numeric codes, and characters',
    category: 'Developer Reference',
    keywords: ['html', 'entity', 'reference', 'character', 'symbol', 'escape'],
  },
  {
    id: 'css-units',
    name: 'CSS Units Reference',
    description: 'Reference for CSS units (px, em, rem, vw, vh, etc.) with descriptions and examples',
    category: 'Developer Reference',
    keywords: ['css', 'units', 'px', 'em', 'rem', 'vw', 'vh', 'reference', 'length'],
  },
  {
    id: 'keyboard-codes',
    name: 'Keyboard Event Codes Reference',
    description: 'Reference for JavaScript keyboard event codes with interactive testing',
    category: 'Developer Reference',
    keywords: ['keyboard', 'event', 'keycode', 'key', 'javascript', 'reference'],
  },
  {
    id: 'mime-types',
    name: 'MIME Type Reference',
    description: 'Comprehensive list of MIME types with file extensions and descriptions',
    category: 'Developer Reference',
    keywords: ['mime', 'type', 'content-type', 'file', 'extension', 'http', 'reference'],
  },
  {
    id: 'color-names',
    name: 'Color Names Reference',
    description: 'All 140+ named CSS colors with HEX, RGB, and HSL values',
    category: 'Developer Reference',
    keywords: ['color', 'css', 'names', 'hex', 'rgb', 'reference', 'web colors'],
  },
  {
    id: 'http-methods',
    name: 'HTTP Methods Reference',
    description: 'Reference for HTTP methods (GET, POST, PUT, DELETE, etc.)',
    category: 'Developer Reference',
    keywords: ['http', 'methods', 'get', 'post', 'put', 'delete', 'reference'],
  },
  {
    id: 'vim-cheat',
    name: 'Vim Cheat Sheet',
    description: 'Vim commands reference',
    category: 'Developer Reference',
    keywords: ['vim', 'cheat sheet', 'commands', 'reference', 'editor'],
  },
  {
    id: 'linux-commands',
    name: 'Linux Commands Cheat Sheet',
    description: 'Common Linux commands reference',
    category: 'Developer Reference',
    keywords: ['linux', 'commands', 'cheat sheet', 'reference', 'terminal', 'bash'],
  },
  {
    id: 'keyboard-shortcuts',
    name: 'Keyboard Shortcuts',
    description: 'IDE & terminal shortcuts reference',
    category: 'Developer Reference',
    keywords: ['keyboard', 'shortcuts', 'hotkeys', 'reference', 'ide', 'terminal'],
  },
  {
    id: 'unicode-search',
    name: 'Unicode Character Search',
    description: 'Search and browse Unicode characters',
    category: 'Developer Reference',
    keywords: ['unicode', 'character', 'search', 'browse', 'code point'],
  },
  {
    id: 'emoji-picker',
    name: 'Emoji Picker',
    description: 'Search and copy emojis',
    category: 'Developer Reference',
    keywords: ['emoji', 'picker', 'search', 'copy', 'smileys'],
  },
]

export const categories = [...new Set(toolDefinitions.map((t) => t.category))]

export function getToolDefinitionById(id: string): ToolDefinition | undefined {
  return toolDefinitions.find((t) => t.id === id)
}
